require('setups.whichkey')
require('setups.treesitter')
require('setups.telescope')
require('setups.comment')
require('setups.lsp')
-- require('setups.hardtime')
require('setups.git')
require('setups.undotree')
require('setups.harpoon2')
